services:
  # Our main Database
  nexus-db:
    image: postgres:16
    container_name: nexus-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nexuspay
    ports:
      - "5432:5432"

  # Our fast Cache for "Bouncer" (Gateway) rules
  nexus-redis:
    image: redis:7
    container_name: nexus-redis
    ports:
      - "6379:6379"

  # A tool to visualize our "Phonebook" later
  nexus-zipkin:
    image: openzipkin/zipkin
    container_name: nexus-zipkin
    ports:
      - "9411:9411"

    # Our Message Broker (The "Post Office")
  nexus-mq:
    image: rabbitmq:3-management
    container_name: nexus-mq
    ports:
      - "5672:5672"   # AMQP protocol (Services use this)
      - "15672:15672" # Management UI (You use this in the browser)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    # Ensures RabbitMQ stays alive and restarts if the computer reboots
    restart: always
