spring.application.name=discovery-server

# Give the phonebook its standard port number
server.port=8761

# Tell it not to register with itself
eureka.client.register-with-eureka=false

#Prevents the server from trying to download registry data from peer servers.
eureka.client.fetch-registry=false
